project_id = "pyironepbibpexuptzst"

[functions.check-commutes]
verify_jwt = true

[functions.places-autocomplete]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
